<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\Exceptions\**" />
    <Compile Remove="Common\Models\**" />
    <Compile Remove="Common\Results\**" />
    <EmbeddedResource Remove="Common\Exceptions\**" />
    <EmbeddedResource Remove="Common\Models\**" />
    <EmbeddedResource Remove="Common\Results\**" />
    <None Remove="Common\Exceptions\**" />
    <None Remove="Common\Models\**" />
    <None Remove="Common\Results\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TAO.AI\TAO.AI.csproj" />
    <ProjectReference Include="..\TAO.Domain\TAO.Domain.csproj" />
    <ProjectReference Include="..\TAO.SharedKernel\TAO.SharedKernel.csproj" />
  </ItemGroup>

</Project>
